# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('PupsToPet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['ID', 'startTime', 'endTime', 'loc', 'host']},
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['name', 'ID', 'gender', 'breed', 'owner']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.AddField(
            model_name='event',
            name='ID',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for each event', primary_key=True, serialize=False),
        ),
    ]
