# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PupsToPet', '0004_auto_20171029_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='breed',
        ),
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.ManyToManyField(help_text='Your pet might be pure-bred or mixed! Select the breed(s) for this pet', to='PupsToPet.Breed'),
        ),
    ]
