# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PupsToPet', '0006_auto_20171029_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='M', help_text="Owner's gender", max_length=1),
        ),
    ]
