# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PupsToPet', '0007_auto_20171029_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(help_text='Event name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='breed',
            name='breed',
            field=models.CharField(help_text='Enter a dog breed (e.g. German Sheperd, Golden Retriever, Poodle)', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='endTime',
            field=models.DateTimeField(help_text='Enter time that event ends', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='loc',
            field=models.CharField(help_text='Enter event location', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='startTime',
            field=models.DateTimeField(help_text='Enter time that event starts', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='additional_notes',
            field=models.TextField(help_text='What else should we know about your pet? Write them down here!', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.ManyToManyField(help_text='Your pet might be pure-bred or mixed! Select the breed(s) for this pet.', to='PupsToPet.Breed'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='disposition',
            field=models.CharField(help_text="Write some notes about your pet's disposition/personality.", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='karma',
            field=models.FloatField(help_text="Pet's average rating", null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(help_text="Pet's owner", null=True, on_delete=django.db.models.deletion.SET_NULL, to='PupsToPet.Owner'),
        ),
    ]
