# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PupsToPet', '0010_auto_20171029_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.RemoveField(
            model_name='event',
            name='pet',
        ),
    ]
