# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PupsToPet', '0011_auto_20171029_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='owner',
            new_name='pets_owner',
        ),
        migrations.AddField(
            model_name='owner',
            name='owners_pets',
            field=models.ForeignKey(help_text="Owner's pet(s)", null=True, on_delete=django.db.models.deletion.SET_NULL, to='PupsToPet.Pet'),
        ),
    ]
