# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PupsToPet', '0014_owner_pet_owner_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='owners_pets',
            field=models.CharField(help_text="Write down your dog's name if you have one. If you have several dogs, write all of them.", max_length=1000, null=True),
        ),
    ]
