# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PupsToPet', '0016_remove_pet_karma'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(help_text='Enter event description here!', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(help_text='Event name', max_length=75, null=True),
        ),
    ]
