# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 14:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(help_text='Enter a dog breed (e.g. German Sheperd, Golden Retriever, Poodle)', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Disposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposition', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('name', models.CharField(help_text='Event name', max_length=75, null=True)),
                ('ID', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for each event', primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(help_text='Enter time that event starts', max_length=10, null=True)),
                ('end_time', models.DateTimeField(help_text='Enter time that event ends', max_length=10, null=True)),
                ('description', models.CharField(help_text='Enter event description here!', max_length=300, null=True)),
                ('location', models.CharField(help_text='Enter event location', max_length=100, null=True)),
            ],
            options={
                'ordering': ['start_time', 'name', 'host', 'ID'],
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, help_text="Owner's unique id", primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('SB', 'Space Bear')], default='SB', max_length=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, help_text="Pet's unique id", primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Enter pet's name", max_length=100, null=True)),
                ('age', models.CharField(help_text="How old is your pet? Enter a number. (ex: '2', '10', or '15')", max_length=2, null=True)),
                ('service', models.BooleanField(default=False, help_text='Is this a service animal?')),
                ('vaccinated', models.BooleanField(default=False, help_text='Is this pet vaccinated?')),
                ('additional_notes', models.TextField(help_text='What else should we know about your pet? Write them down here!', max_length=1000, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='M', help_text="Pet's gender", max_length=1)),
                ('size', models.CharField(blank=True, choices=[('S', 'small'), ('M', 'medium'), ('L', 'large')], help_text="Pet's size", max_length=1)),
                ('breed', models.ManyToManyField(help_text='Your pet might be pure-bred or mixed! Select the breed(s) for this pet.', to='PupsToPet.Breed')),
                ('disposition', models.ManyToManyField(help_text="Write some notes about your pet's disposition/personality.", to='PupsToPet.Disposition')),
                ('owner', models.ForeignKey(help_text="Pet's owner", null=True, on_delete=django.db.models.deletion.SET_NULL, to='PupsToPet.Owner')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.ForeignKey(help_text='Host of event', null=True, on_delete=django.db.models.deletion.SET_NULL, to='PupsToPet.Owner'),
        ),
        migrations.AddField(
            model_name='event',
            name='pets',
            field=models.ManyToManyField(help_text='Pets attending event', to='PupsToPet.Pet'),
        ),
    ]
