# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PupsToPet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='disposition',
        ),
        migrations.AddField(
            model_name='pet',
            name='disposition',
            field=models.CharField(help_text="Write some notes about your pet's disposition/personality.", max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Disposition',
        ),
    ]
