# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PupsToPet', '0002_auto_20171212_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposition', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='pet',
            name='disposition',
        ),
        migrations.AddField(
            model_name='pet',
            name='disposition',
            field=models.ManyToManyField(help_text="Write some notes about your pet's disposition/personality.", to='PupsToPet.Disposition'),
        ),
    ]
