# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PupsToPet', '0002_auto_20171029_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(help_text='Enter a book genre (e.g. German Sheperd, Golden Retriever, Poodle)', max_length=200)),
            ],
        ),
    ]
