# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PupsToPet', '0003_auto_20171212_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='disposition',
        ),
        migrations.AddField(
            model_name='pet',
            name='disposition',
            field=models.CharField(help_text="Write some notes about your pet's disposition/personality.", max_length=200, null=True),
        ),
    ]
