# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PupsToPet', '0017_auto_20171031_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='owners_pets',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='pet_owner_status',
        ),
        migrations.AddField(
            model_name='event',
            name='pet',
            field=models.ManyToManyField(help_text='Pets attending event', to='PupsToPet.Pet'),
        ),
    ]
