# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PupsToPet', '0017_auto_20171031_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='owners_pets',
        ),
    ]
