# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PupsToPet', '0018_remove_owner_owners_pets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='pet_owner_status',
        ),
    ]
