# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 18:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PupsToPet', '0019_auto_20171101_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='email',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='username',
        ),
        migrations.AddField(
            model_name='event',
            name='pets',
            field=models.ManyToManyField(help_text='Pets attending event', to='PupsToPet.Pet'),
        ),
        migrations.AddField(
            model_name='owner',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
