# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='owner name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='pet name', max_length=100)),
                ('owner', models.ForeignKey(help_text='owner of pet', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pupapp.Owner')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.ForeignKey(help_text='host of event', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pupapp.Owner'),
        ),
        migrations.AddField(
            model_name='event',
            name='pet',
            field=models.ManyToManyField(help_text='pets attending event', to='pupapp.Pet'),
        ),
    ]
