# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pupapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['startTime', 'id']},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'ordering': ['lastName', 'firstName', 'id']},
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['name', 'id']},
        ),
        migrations.RemoveField(
            model_name='owner',
            name='name',
        ),
        migrations.AddField(
            model_name='event',
            name='endTime',
            field=models.CharField(help_text='time that event ends', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='loc',
            field=models.CharField(help_text='location event takes place', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='startTime',
            field=models.CharField(help_text='time that event starts', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='email',
            field=models.CharField(help_text="owner's email adress", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='firstName',
            field=models.CharField(help_text="owner's first name", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], help_text="Owner's gender", max_length=1),
        ),
        migrations.AddField(
            model_name='owner',
            name='lastName',
            field=models.CharField(help_text="owner's last name", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='username',
            field=models.CharField(help_text="owner's username", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='additional_notes',
            field=models.CharField(help_text='misc notes about pet', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.CharField(help_text='pet breed', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='disposition',
            field=models.CharField(help_text="notes about pet's disposition", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='M', help_text="Pet's gender", max_length=1),
        ),
        migrations.AddField(
            model_name='pet',
            name='karma',
            field=models.FloatField(help_text='average rating of pet', null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='service',
            field=models.BooleanField(default=False, help_text='is this a service animal'),
        ),
        migrations.AddField(
            model_name='pet',
            name='vacinated',
            field=models.BooleanField(default=False, help_text='is this pet vacinated'),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for each event', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='owner',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for each owner', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pet',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for each pet', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(help_text='pet name', max_length=100, null=True),
        ),
    ]
