# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupapp', '0004_auto_20171024_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='additional_notes',
            field=models.TextField(help_text='summary and additional notes about pet', max_length=1000, null=True),
        ),
    ]
