# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 20:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PupsToPet', '0005_auto_20171029_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={},
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='owners_pet',
        ),
    ]
