# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for each event', primary_key=True, serialize=False)),
                ('startTime', models.DateTimeField(help_text='time that event starts', max_length=10, null=True)),
                ('endTime', models.DateTimeField(help_text='time that event ends', max_length=10, null=True)),
                ('loc', models.CharField(help_text='location event takes place', max_length=100, null=True)),
            ],
            options={
                'ordering': ['startTime', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for each owner', primary_key=True, serialize=False)),
                ('firstName', models.CharField(help_text="owner's first name", max_length=100, null=True)),
                ('lastName', models.CharField(help_text="owner's last name", max_length=100, null=True)),
                ('username', models.CharField(help_text="owner's username", max_length=100, null=True)),
                ('email', models.EmailField(help_text="owner's email adress", max_length=254, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], help_text="Owner's gender", max_length=1)),
            ],
            options={
                'ordering': ['username', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for each pet', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='pet name', max_length=100, null=True)),
                ('breed', models.CharField(help_text='pet breed', max_length=25, null=True)),
                ('karma', models.FloatField(help_text='average rating of pet', null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='M', help_text="Pet's gender", max_length=1)),
                ('service', models.BooleanField(default=False, help_text='is this a service animal')),
                ('vacinated', models.BooleanField(default=False, help_text='is this pet vacinated')),
                ('disposition', models.CharField(help_text="notes about pet's disposition", max_length=200, null=True)),
                ('additional_notes', models.TextField(help_text='summary and additional notes about pet', max_length=1000, null=True)),
                ('owner', models.ForeignKey(help_text='owner of pet', null=True, on_delete=django.db.models.deletion.SET_NULL, to='PupsToPet.Owner')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.ForeignKey(help_text='host of event', null=True, on_delete=django.db.models.deletion.SET_NULL, to='PupsToPet.Owner'),
        ),
        migrations.AddField(
            model_name='event',
            name='pet',
            field=models.ManyToManyField(help_text='pets attending event', to='PupsToPet.Pet'),
        ),
    ]
