# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField(help_text='time that event starts', max_length=10, null=True)),
                ('endTime', models.DateTimeField(help_text='time that event ends', max_length=10, null=True)),
                ('loc', models.CharField(help_text='location event takes place', max_length=100, null=True)),
            ],
            options={
                'ordering': ['startTime', 'endTime', 'loc', 'host'],
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, help_text="Owner's unique id", primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text="Owner's first name", max_length=100, null=True)),
                ('last_name', models.CharField(help_text="Owner's last name", max_length=100, null=True)),
                ('username', models.CharField(help_text="Owner's username", max_length=100, null=True)),
                ('email', models.EmailField(help_text='email address', max_length=254, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='M', help_text="Pet's gender", max_length=1)),
            ],
            options={
                'ordering': ['username', 'ID'],
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, help_text="Pet's unique id", primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Enter pet's name", max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='M', help_text="Pet's gender", max_length=1)),
                ('breed', models.CharField(help_text="Pet's breed", max_length=25, null=True)),
                ('age', models.CharField(help_text="age (ex: '2', '10', or '15')", max_length=2, null=True)),
                ('size', models.CharField(blank=True, choices=[('S', 'small'), ('M', 'medium'), ('L', 'large')], help_text="Pet's size", max_length=1)),
                ('karma', models.FloatField(help_text="pet's average rating", null=True)),
                ('service', models.BooleanField(default=False, help_text='Is this a service animal?')),
                ('vaccinated', models.BooleanField(default=False, help_text='Is this pet vaccinated?')),
                ('disposition', models.CharField(help_text="notes about Pet's disposition", max_length=200, null=True)),
                ('additional_notes', models.TextField(help_text="owner's additionsal notes about his/her pet", max_length=1000, null=True)),
                ('owner', models.ForeignKey(help_text="pet's owner", null=True, on_delete=django.db.models.deletion.SET_NULL, to='PupsToPet.Owner')),
            ],
            options={
                'ordering': ['name', 'ID'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.ForeignKey(help_text='host of event', null=True, on_delete=django.db.models.deletion.SET_NULL, to='PupsToPet.Owner'),
        ),
        migrations.AddField(
            model_name='event',
            name='pet',
            field=models.ManyToManyField(help_text='pets attending event', to='PupsToPet.Pet'),
        ),
    ]
