# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PupsToPet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(help_text='Enter a dog breed (e.g. German Sheperd, Golden Retriever, Poodle)', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='pet',
            name='breed',
        ),
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.ManyToManyField(help_text='Your pet might be pure-bred or mixed! Select the breed(s) for this pet.', to='PupsToPet.Breed'),
        ),
    ]
