# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PupsToPet', '0002_auto_20171031_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='karma',
        ),
    ]
