# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PupsToPet', '0003_breed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={'ordering': ['ID', 'username', 'firstName', 'lastName', 'email', 'gender']},
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={},
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='last_name',
            new_name='lastName',
        ),
        migrations.AddField(
            model_name='owner',
            name='owners_pet',
            field=models.CharField(help_text="Owner's pets", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(help_text="Enter pet's breed", max_length=100, null=True),
        ),
    ]
