# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 06:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PupsToPet', '0018_auto_20171031_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_time', 'name', 'host', 'ID']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='pet',
        ),
    ]
